# .github/workflows/scrape_static.yml
name: Monthly Holo Scraper

on:
  schedule:
    - cron: '0 0 1 * *'  # monthly at 00:00 on the 1st
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    env:
      DB_URL: ${{ secrets.DB_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Setup Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          install-chromedriver: true
          install-dependencies: true

      - name: Run scraper
        run: python scrapers/scrape_static_holo.py
